### ISSUE TITLE
v0.0.12 Linux x86_64 build does not have the -ipfsaddr flag

### ISSUE THREAD

**Issue by 5310** [FleekHQ/space-daemon#110]
The [readme mentions an `-ipfsaddr` flag](https://github.com/FleekHQ/space-daemon#ipfs-node) that lets the daemon use an existing IPFS node. But the Linux binary doesn't support it:

```
$ ./space_Linux_x86_64 -ipfsaddr=/ip4/127.0.0.1/tcp/5001
flag provided but not defined: -ipfsaddr
Usage of ./space_Linux_x86_64:
  -cpuprofile file
    	write cpu profile to file
  -debug
    	run daemon with debug mode for profiling (default true)
  -dev
    	run daemon in dev mode to use .env file
  -memprofile file
    	write memory profile to file
```

**Comment by jsonsivar** [comment]
Hey @5310, thank you for reporting this and apologies for the delayed response. It's been really busy and somehow this was missed. This is a good catch and we are currently enhancing the way IPFS works in this PR #112 and the fix for this is included in that PR.  Note there will be an update to that section of the readme to indicate how to use your own node so will post here once that is reflected and merged.
